from PyQt5 import QtWidgets

class ExcelGroup(QtWidgets.QGroupBox):
    def __init__(self, parent=None):
        super().__init__("Configurazione Excel", parent)
        layout = QtWidgets.QVBoxLayout()
        excel_layout = QtWidgets.QHBoxLayout()
        excel_label = QtWidgets.QLabel("File Excel:")
        self.excel_path_edit = QtWidgets.QLineEdit()
        self.excel_path_edit.setPlaceholderText("Nessun file selezionato")
        self.excel_path_edit.setReadOnly(True)
        self.browse_btn = QtWidgets.QPushButton("Sfoglia")
        excel_layout.addWidget(excel_label)
        excel_layout.addWidget(self.excel_path_edit)
        excel_layout.addWidget(self.browse_btn)
        layout.addLayout(excel_layout)
        matricola_layout = QtWidgets.QHBoxLayout()
        matricola_label = QtWidgets.QLabel("Matricola:")
        self.matricola_edit = QtWidgets.QLineEdit()
        self.matricola_edit.setPlaceholderText("Inserire matricola...")
        self.matricola_dec_btn = QtWidgets.QPushButton("−")
        self.matricola_dec_btn.setFixedWidth(50)
        self.matricola_inc_btn = QtWidgets.QPushButton("+")
        self.matricola_inc_btn.setFixedWidth(50)
        matricola_layout.addWidget(matricola_label)
        matricola_layout.addWidget(self.matricola_edit)
        matricola_layout.addWidget(self.matricola_dec_btn)
        matricola_layout.addWidget(self.matricola_inc_btn)
        layout.addLayout(matricola_layout)
        self.setLayout(layout)
